### ISSUE TITLE
Warning: failed loading '/etc/yum.repos.d/CentOS-Vault.repo', skipping.

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-cis#3]
## Describe the bug
These tasks break the CentOS-Vault.repo file:

```yaml
- name: 1.2.2 Ensure gpgcheck is globally activated (Scored)
  find:
    paths: /etc/yum.repos.d/
    patterns: '*'
  register: cis_repos
  when:
    - cis_gpgcheck_enabled | bool

- name: 1.2.2 Ensure gpgcheck is globally activated (Scored)
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^gpgcheck='
    line: gpgcheck=1
  loop: "{{ cis_repos.files }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - cis_gpgcheck_enabled | bool
```
