### ISSUE TITLE
/tmp not mounted, tmp.mount not started

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-cis#4]
## Describe the bug
Even though the service `tmp.mount` is started:

```yaml
- name: 1.1.2 Ensure /tmp is configured (Scored)
  systemd:
    name: tmp.mount
    state: started
    enabled: yes
  when:
    - cis_tmp_configured | bool
```

And the task report as changed:

```
TASK [robertdebock.cis : 1.1.2 Ensure /tmp is configured (Scored)] *************
changed: [centos8]
```

The service is not running:

```
[vagrant@localhost ~]$ systemctl status tmp.mount
● tmp.mount - Temporary Directory (/tmp)
   Loaded: loaded (/usr/lib/systemd/system/tmp.mount; disabled; vendor preset: >
   Active: inactive (dead)
    Where: /tmp
     What: tmpfs
     Docs: man:hier(7)
           https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
```

And thus /tmp is not mounted:

```
[vagrant@localhost ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        475M     0  475M   0% /dev
tmpfs           490M     0  490M   0% /dev/shm
tmpfs           490M  6.6M  484M   2% /run
tmpfs           490M     0  490M   0% /sys/fs/cgroup
/dev/vda1        10G  3.8G  6.3G  38% /
tmpfs            98M     0   98M   0% /run/user/1000
```
