### ISSUE TITLE
Reduce the amount of `assert` statements

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-cis#5]
## Describe the bug

There are many tasks that `assert` the outcome of a previous task. This can be simplified by using `failed_when` in the same task.

For example:

```
- name: 1.1.2 Ensure /tmp is configured (Scored)
  command: systemctl is-enabled tmp.mount
  register: output_systemctl
  when:
    - cis_tmp_configured | bool

- name: 1.1.2 Ensure /tmp is configured (Scored)
  assert:
    that:
      - output_fstab.stdout_lines | length > 0 or
        output_systemctl.stdout in ["static", "enabled"]
  when:
    - cis_tmp_configured | bool
    - output_fstab.stdout_lines is defined
```
