### ISSUE TITLE
Registered variable names are inconsistent

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-cis#6]
## Describe the bug
Some `register`ed variables have weird names:

```
- name: 1.1.2 Ensure /tmp is configured (Scored)
  command: systemctl is-enabled tmp.mount
  register: output_systemctl
  when:
    - cis_tmp_configured | bool

- name: 1.1.2 Ensure /tmp is configured (Scored)
  assert:
    that:
      - output_fstab.stdout_lines | length > 0 or
        output_systemctl.stdout in ["static", "enabled"]
  when:
    - cis_tmp_configured | bool
    - output_fstab.stdout_lines is defined
```

I suggest to use the variable name used in `defaults/main.yml` and add `test` or `test_one`, `test_two`, etc.
